/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Inhr1.c
**     Project     : kit2_comandos
**     Processor   : MCF52259CAG80
**     Component   : AsynchroSerial
**     Version     : Component 02.611, Driver 01.02, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2017-06-06, 11:35, # CodeGen: 45
**     Abstract    :
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
**     Settings    :
**         Serial channel              : UART1
**
**         Protocol
**             Init baud rate          : 9600baud
**             Width                   : 8 bits
**             Stop bits               : 1.000
**             Parity                  : none
**             Breaks                  : Disabled
**             Input buffer size       : 0
**             Output buffer size      : 2
**
**         Registers
**             Input buffer            : URB1      [0x024C]
**             Output buffer           : UTB1      [0x024C]
**             Control register        : UMR11     [0x0240]
**             Mode register           : UMR21     [0x0240]
**             Baud setting reg.       : UCSR1     [0x0244]
**
**         Input interrupt
**             Vector name             : INT_UART1
**             Priority                : 430
**
**         Output interrupt
**             Vector name             : INT_UART1
**             Priority                : 430
**
**         Used pins:
**         ----------------------------------------------------------
**           Function | On package           |    Name
**         ----------------------------------------------------------
**            Input   |     63               |  URXD1_I2C_SDA1_PUB1
**            Output  |     62               |  UTXD1_I2C_SCL1_PUB0
**         ----------------------------------------------------------
**
**
**
**     Contents    :
**         RecvChar        - byte Inhr1_RecvChar(Inhr1_TComData *Chr);
**         SendChar        - byte Inhr1_SendChar(Inhr1_TComData Chr);
**         GetCharsInRxBuf - word Inhr1_GetCharsInRxBuf(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Inhr1.c
** @version 01.02
** @brief
**         This component "AsynchroSerial" implements an asynchronous serial
**         communication. The component supports different settings of
**         parity, word width, stop-bit and communication speed,
**         user can select interrupt or polling handler.
**         Communication speed can be changed also in runtime.
**         The component requires one on-chip asynchronous serial channel.
*/         
/*!
**  @addtogroup Inhr1_module Inhr1 module documentation
**  @{
*/         

/* MODULE Inhr1. */

#include "Inhr1.h"
#include "Events.h"


#define OVERRUN_ERR      0x01          /* Overrun error flag bit    */
#define FRAMING_ERR      0x02          /* Framing error flag bit    */
#define PARITY_ERR       0x04          /* Parity error flag bit     */
#define CHAR_IN_RX       0x08          /* Char is in RX buffer      */
#define FULL_TX          0x10          /* Full transmit buffer      */
#define RUNINT_FROM_TX   0x20          /* Interrupt is in progress  */
#define FULL_RX          0x40          /* Full receive buffer       */
#define ENABLED_TX_INT   0x80          /* TX interrupt enabled      */
#define BREAK_ERR        0x0200        /* Break detect              */
#define COMMON_ERR       0x0800        /* Common error of RX       */

static volatile word SerFlag;          /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Framing error */
                                       /*       2 - Parity error */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - TX interrupt enabled */
                                       /*       8 - Unused  */
                                       /*       9 - Break detected  */
                                       /*      10 - Unused */
                                       /*      11 - Unused */
static volatile Inhr1_TComData BufferRead; /* Input char for serial commmunication */
volatile word Inhr1_OutLen;            /* Length of output bufer's content */
static volatile Inhr1_TComData *OutPtrR; /* Pointer for reading from output buffer */
static volatile Inhr1_TComData *OutPtrW; /* Pointer for writing to output buffer */
static volatile Inhr1_TComData OutBuffer[Inhr1_OUT_BUF_SIZE]; /* Output buffer for serial commmunication */

/*
** ===================================================================
**     Method      :  HWEnDi (component AsynchroSerial)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void HWEnDi(void)
{
  setReg8(UCR1, (UCR1_TC0_BITMASK | UCR1_RC0_BITMASK)); /* Enable receiver and transmitter */
  setReg8(UIMR1, 0x02);                /* Enable receiver interrupt */
}

/*
** ===================================================================
**     Method      :  Inhr1_RecvChar (component AsynchroSerial)
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). This method is enabled only if the receiver property
**         is enabled.
**         [Note:] Because the preferred method to handle error and
**         break exception in the interrupt mode is to use events
**         <OnError> and <OnBreak> the return value ERR_RXEMPTY has
**         higher priority than other error codes. As a consequence the
**         information about an exception in interrupt mode is returned
**         only if there is a valid character ready to be read.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - Pointer to a received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_RXEMPTY - No data in receiver
**                           ERR_BREAK - Break character is detected
**                           (only when the <Interrupt service> property
**                           is disabled and the <Break signal> property
**                           is enabled)
**                           ERR_COMMON - common error occurred (the
**                           <GetError> method can be used for error
**                           specification)
** ===================================================================
*/
byte Inhr1_RecvChar(Inhr1_TComData *Chr)
{
  register byte Result = ERR_OK;       /* Return error code */

  if (!(SerFlag & CHAR_IN_RX)) {       /* Is any char in RX buffer? */
    return ERR_RXEMPTY;                /* If no then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  *Chr = BufferRead;                   /* Received char */
  Result = (byte)((SerFlag & (OVERRUN_ERR | COMMON_ERR))? ERR_COMMON : ERR_OK);
  SerFlag &= ~(OVERRUN_ERR | COMMON_ERR | CHAR_IN_RX); /* Clear all errors in the status variable */
  ExitCritical();                      /* Enable global interrupts */
  return Result;                       /* Return error code */
}

/*
** ===================================================================
**     Method      :  Inhr1_SendChar (component AsynchroSerial)
**     Description :
**         Sends one character to the channel. If the component is
**         temporarily disabled (Disable method) SendChar method only
**         stores data into an output buffer. In case of a zero output
**         buffer size, only one character can be stored. Enabling the
**         component (Enable method) starts the transmission of the
**         stored data. This method is available only if the
**         transmitter property is enabled.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte Inhr1_SendChar(Inhr1_TComData Chr)
{
  if (Inhr1_OutLen == Inhr1_OUT_BUF_SIZE) { /* Is number of chars in buffer is the same as a size of the transmit buffer */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Disable global interrupts */
  Inhr1_OutLen++;                      /* Increase number of bytes in the transmit buffer */
  *(OutPtrW++) = Chr;                  /* Store char to buffer */
  if (OutPtrW >= (OutBuffer + Inhr1_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer */
    OutPtrW = OutBuffer;               /* Set pointer to first item in the transmit buffer */
  }
  SerFlag |= ENABLED_TX_INT;           /* Set the flag ENABLED_TX_INT */
  setReg8(UIMR1, 0x03);                /* Enable transmit interrupt */
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  Inhr1_GetCharsInRxBuf (component AsynchroSerial)
**     Description :
**         Returns the number of characters in the input buffer. This
**         method is available only if the receiver property is enabled.
**     Parameters  : None
**     Returns     :
**         ---             - The number of characters in the input
**                           buffer.
** ===================================================================
*/
word Inhr1_GetCharsInRxBuf(void)
{
  return (word)(((SerFlag & CHAR_IN_RX) != 0x00)? 1 : 0); /* Return number of chars in receive buffer */
}

/*
** ===================================================================
**     Method      :  Inhr1_InterruptRx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR    1
#define ON_FULL_RX  2
#define ON_RX_CHAR  4
static void Inhr1_InterruptRx(void)
{
  register Inhr1_TComData Data;        /* Temporary variable for data */
  register byte OnFlags = 0x00;        /* Temporary variable for flags */

  Data = (Inhr1_TComData)getReg8(URB1); /* Read data from the receiver */
  if (SerFlag & CHAR_IN_RX) {          /* Is any char already present in the receive buffer? */
    SerFlag |= OVERRUN_ERR;            /* If yes then set flag OVERRUN_ERR */
  } else {
    BufferRead = Data;
    SerFlag |= CHAR_IN_RX;             /* Set flag "char in RX buffer" */
    OnFlags |= ON_RX_CHAR;             /* Set flag "OnRxChar" */
  }
  if (OnFlags & ON_RX_CHAR) {          /* Is OnRxChar flag set? */
    __EI(7);                           /* Set the event interrupt priority */
    Inhr1_OnRxChar();                  /* If yes then invoke user event */
  }
  __EI(4);                             /* Restore interrupt priority */
}

/*
** ===================================================================
**     Method      :  Inhr1_InterruptTx (component AsynchroSerial)
**
**     Description :
**         The method services the receive interrupt of the selected 
**         peripheral(s) and eventually invokes the component's event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_FREE_TX  1
#define ON_TX_CHAR  2
static void Inhr1_InterruptTx(void)
{
  register byte OnFlags = 0x00;        /* Temporary variable for flags */

  if (SerFlag & RUNINT_FROM_TX) {      /* Is flag "running int from TX" set? */
    OnFlags |= ON_TX_CHAR;             /* Set flag "OnTxChar" */
  }
  SerFlag &= ~RUNINT_FROM_TX;          /* Reset flag "running int from TX" */
  if (Inhr1_OutLen) {                  /* Is number of bytes in the transmit buffer greater then 0? */
    Inhr1_OutLen--;                    /* Decrease number of chars in the transmit buffer */
    SerFlag |= RUNINT_FROM_TX;         /* Set flag "running int from TX"? */
    setReg8(UTB1, (Inhr1_TComData)*(OutPtrR++)); /* Store char to transmitter register */
    if (OutPtrR >= (OutBuffer + Inhr1_OUT_BUF_SIZE)) { /* Is the pointer out of the transmit buffer? */
      OutPtrR = OutBuffer;             /* Set pointer on the first item into the transmit buffer */
    }
  } else {
    SerFlag &= ~ENABLED_TX_INT;        /* Clear the flag ENABLED_TX_INT */
    setReg8(UIMR1, 0x02);              /* Disable transmit interrupt */
  }
  if (OnFlags & ON_TX_CHAR) {          /* Is flag "OnTxChar" set? */
    __EI(7);                           /* Set the event interrupt priority */
    Inhr1_OnTxChar();                  /* If yes then invoke user event */
  }
  __EI(4);                             /* Restore interrupt priority */
}

/*
** ===================================================================
**     Method      :  Inhr1_Interrupt (component AsynchroSerial)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
__declspec(interrupt) void Inhr1_Interrupt(void)
{
  register word StatReg = getReg8(USR1); /* Read status register */

  if (StatReg & (USR1_RB_BITMASK | USR1_OE_BITMASK | USR1_FE_BITMASK | USR1_PE_BITMASK)) { /* Is any error flag set? */
    setReg8(UCR1, 0x40);               /* Reset error request flags */
    if (StatReg & USR1_RB_BITMASK) {   /* Is break detected? */
      SerFlag |= FRAMING_ERR;          /* If yes then set the flag */
    }
    if (StatReg & (USR1_OE_BITMASK | USR1_FE_BITMASK | USR1_PE_BITMASK)) { /* Is an error detected? */
      SerFlag |= COMMON_ERR;           /* If yes then set an internal flag */
    }
    (void)getReg8(URB1);               /* Dummy read of data register - clear RXRDY bit */
    StatReg &= ~USR1_RXRDY_BITMASK;    /* Clear the receive data flag to discard the errorneous data */
  }
  if (StatReg & USR1_RXRDY_BITMASK) {  /* Is the receiver interrupt flag set? */
    Inhr1_InterruptRx();               /* If yes, then invoke the internal service routine. This routine is inlined. */
  }
  if (SerFlag & ENABLED_TX_INT) {      /* Is the transmitter interrupt enabled? */
    if (StatReg & USR1_TXRDY_BITMASK) { /* Is the transmitter ready? */
      Inhr1_InterruptTx();             /* If yes, then invoke the internal service routine. This routine is inlined. */
    }
  }
}

/*
** ===================================================================
**     Method      :  Inhr1_Init (component AsynchroSerial)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Inhr1_Init(void)
{
  SerFlag = 0x00;                      /* Reset flags */
  /* UCR1: ??=0,MISC=3,TC=0,RC=0 */
  setReg8(UCR1, 0x30U);                /* Reset UART transmitter */ 
  /* UCR1: ??=0,MISC=2,TC=0,RC=0 */
  setReg8(UCR1, 0x20U);                /* Reset UART receiver */ 
  /* UMR11: RXRTS=0,RXIRQ=0,ERR=0,PM=2,PT=0,BC=3 */
  setReg8(UMR11, 0x13U);               /*  Set the UMR1 register */ 
  /* UMR21: CM=0,TXRTS=0,TXCTS=0,SB=7 */
  setReg8(UMR21, 0x07U);               /*  Set the UMR2 register */ 
  /* UCSR1: RCS=0x0D,TCS=0x0D */
  setReg8(UCSR1, 0xDDU);                
  Inhr1_OutLen = 0x00;                 /* No char in the transmit buffer */
  OutPtrW = OutPtrR = OutBuffer;       /* Set pointer on the first item in the transmit buffer */
  /* UBG11: Divider_MSB=1 */
  setReg8(UBG11, 0x01U);                
  /* UBG21: Divider_LSB=4 */
  setReg8(UBG21, 0x04U);                
  HWEnDi();                            /* Enable/disable device according to status flags */
}


/* END Inhr1. */


/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
