/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : I2C1.h
**     Project     : I2C
**     Processor   : MCF52259CAG80
**     Component   : Init_I2C
**     Version     : Component 01.003, Driver 01.03, CPU db: 3.00.000
**     Compiler    : CodeWarrior MCF C Compiler
**     Date/Time   : 2017-06-20, 19:16, # CodeGen: 8
**     Abstract    :
**          This file implements the I2C (I2C1) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : I2C1
**          Device                                         : I2C1
**          Settings                                       : 
**            Clock setting                                : 
**              Clock divisor select value                 : divide by 224
**              I2C frequency                              : 357.1429 kHz
**            Master/Slave mode select                     : Master
**            Transmit/Receive mode select                 : Transmit
**            Transmit acknowledge                         : yes
**            Slave address                                : 69
**          Pins                                           : 
**            SDA pin                                      : Enabled
**              Pin                                        : URXD1_I2C_SDA1_PUB1
**              Pin signal                                 : 
**            CLK pin                                      : Enabled
**              Pin                                        : UTXD1_I2C_SCL1_PUB0
**              Pin signal                                 : 
**          Interrupts/DMA                                 : 
**            I2C interrupt/DMA                            : 
**              Interrupt                                  : INT_I2C1_IIF
**              Request                                    : Disabled
**              Level                                      : Disabled
**              Priority                                   : 0 (Lowest)
**              ISR Name                                   : 
**              I2C request                                : Disabled
**              I2C request type                           : Interrupt
**          Initialization                                 : 
**            Module enable                                : yes
**            Call Init method                             : yes
**     Contents    :
**         Init - void I2C1_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file I2C1.h
** @version 01.03
** @brief
**          This file implements the I2C (I2C1) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup I2C1_module I2C1 module documentation
**  @{
*/         

#ifndef I2C1_H_
#define I2C1_H_

/* MODULE I2C1. */

/* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


void I2C1_Init(void);
/*
** ===================================================================
**     Method      :  I2C1_Init (component Init_I2C)
**     Description :
**         This method initializes registers of the I2C module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/


/* END I2C1. */
#endif /* #ifndef __I2C1_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale MCF series of microcontrollers.
**
** ###################################################################
*/
